---
- hosts: all
  tasks:
      - name: gather facts
        setup: 

- hosts: localhost
  roles:
      - etcd-ca-init
      - etcd-ca-gen-certs
    
- hosts: etcd-members
  roles: 
      - etcd-member


#- hosts: etcd-proxies
#  roles:
#      - etcd-proxy
