---
- name: Render etcd.env template
  template: >
      src=etcd.env.j2
      dest=/etc/etcd/etcd.env
- name: Render etcdctl.sh template
  template: >
      src=etcdctl.sh.j2
      dest=/usr/sbin/etcdctl.sh
      mode=555
- name: Synchronzie security files
  copy: >
      src={{ etcd_root_path }}/{{ item }}
      dest=/etc/etcd/
      owner=etcd
      group=etcd
      mode=440
  with_items:
      - ca.crt
      - "{{ inventory_hostname }}.crt"
      - "{{ inventory_hostname }}.key.insecure"
- name: restart etcd
  service: >
      name=etcd
      enabled=yes
      state=restarted
