---
- name: Create new certificate
  shell: >
      creates={{ etcd_depot_path }}/{{ cert_host }}.host.csr
      chdir={{ etcd_root_path }}
      etcd-da {{ cert_host }} --domain {{ etcd_domain }} --passphrase {{ etcd_passphrase }}
- name: Sign certificate
  shell: >
      creates={{ etcd_depot_path }}/{{ cert_subject}}.host.crt
      chdir={{ etcd_root_path }}
      etcd-da {{ cert_host }} --passphrase {{ etcd_passphrase }}
